// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emebqxnmdymolcrastas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZWJxeG5tZHltb2xjcmFzdGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDE5MjksImV4cCI6MjA2NjQ3NzkyOX0.K6oLBOEx_g4hdIUEZYKrssLMEGYt47oAhep7ihojz2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);